#!/bin/bash
extra='"'
green='\033[1;32m'
sc='\033[0m'
clear
echo -e "\033[0;34m━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━\033[0m"
echo -e "\E[41;1;37m     • ADICIONAR NA LISTA •  \E[0m"
echo -e "\033[0;34m━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━\033[0m"
read -p "$(echo -e $green"Digite o nome do canal: "$sc)" channel_name
sleep 2s
echo
read -p "$(echo -e $green"Digite sua categoria: "$sc)" group_name
sleep 2s
echo
read -p "$(echo -e $green"Digite a url do Canal: "$sc)" channel_url
sleep 2s
clear
echo -e "\033[0;34mAdicionando Canal...\033[0m"
sleep 2s
clear
echo -e "\033[0;34mCanal Adicionado com Sucesso! \033[0m"
sleep 2s
echo
echo -e "\033[1;31mSalvo na memória do seu dispositivo\033[0m"
echo "#EXTM3U" >> ~/list-iptv.txt
echo "#EXTINF:-0 group-title=${extra}$group_name${extra}, $channel_name" >> ~/list-iptv.txt
echo "$channel_url" >> ~/list-iptv.txt
echo >> ~/list-iptv.txt
cp list-iptv.txt /sdcard
sleep 4s
clear
curl -sO https://raw.githubusercontent.com/Savitar44/iptv-gen/main/menu && bash menu
