#!/bin/bash
clear
rm -rf list-iptv-gen
rm -rf list_rm
echo -e "\033[0;34m━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━\033[0m"
echo -e "\E[41;1;37m     • GERADOR DE LISTA IPTV • \E[0m"
echo -e "\033[0;34m━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━\033[0m"
echo -e "\033[0m\033[01;37m(1) \033[01;33mADICIONAR CANAL\033[0m"
echo -e "\033[0m\033[01;37m(2) \033[01;33mESVAZIAR LISTA\033[0m"
echo -e "\033[0m\033[01;37m(3) \033[01;33mSAIR\033[0m"
echo -e "\033[0;34m━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━\033[0m"
echo -e "\033[1;32m O QUE DESEJA FAZER \033[1;33m?\033[1;31m?\033[1;37m : "
read option

   case $option in
   (1)
   curl -sO https://raw.githubusercontent.com/Savitar44/iptv-gen/main/list-iptv-gen && bash list-iptv-gen
   ;;
   (2)
   curl -sO https://raw.githubusercontent.com/Savitar44/iptv-gen/main/list_rm && bash list_rm
   ;;
   (3)
   clear
   exit
   ;;
   (*) echo -e "\033[1,31mOpção inválida! \033[0m"
   curl -sO https://raw.githubusercontent.com/Savitar44/iptv-gen/main/menu && bash menu

esac
